# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52db3047f020cb6d8ac909bf0d6b21dd5e034ab14d72b9a6d88428933e284c3b0c0141d10666843c08e863e01d1f260fa0985adbdd4d1b6f4c2ebd204987d6f2

test:
  secret_key_base: d0a7163f7ec6f28b72c690ed23b03b3721521db708bece13144948519fd84ce538d8c34b7d318dc207d3e97a8f8e5b08152cbc89cc01bed229091d85d1741f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
